### ISSUE TITLE
好像存在pom.xml中依赖包找不到的问题

### ISSUE THREAD

**Issue by li57598** [Dorae132/ndisconf#1]
有的库中央仓库都找不到，比如
<artifactId>javax.xml</artifactId>

**Comment by li57598** [comment]
这个版本server端启动后访问localhost:8080报以下错误，楼主旧版的不会报错：
Circular view path [/index]: would dispatch back to the current handler URL [/index] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

**Comment by li57598** [comment]
版主，楼上那个错误怎么解决呀，网上找了很多版本都不好用，就你这个版本是最符合我项目需求的，希望能解决一下Circular view path [/index]: would dispatch back to the current handler URL [/index] again. Check your ViewResolver setup! 这个问题，感激不尽！！！

**Comment by Dorae132** [comment]
不应该出现的吧？之前这个问题已经修复了，是不是修改了某些jar的版本？
